services:
  mongo:
    image: mongo:latest
    container_name: factum-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: factum-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

  backend:
    build: ./backend
    container_name: factum-backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/factum
      - STEAM_API_KEY=${STEAM_API_KEY}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: factum-frontend
    ports:
      - 4200:80
    depends_on:
      - backend